name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo (Extension Version)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo Site
        run: hugo --minify --themesDir=themes

      - name: Cache Hugo and Theme
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/bin/hugo
            themes/hugo-theme-stack
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/go.sum') }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:./public