name: Deploy Hugo Site

on:
  push:
    branches:
      - main # 触发部署的分支，可以根据实际情况修改

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Fetch Theme
        run: |
          git clone https://github.com/CaiJimmy/hugo-theme-stack.git themes/hugo-theme-stack

      - name: Build Hugo Site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:./public